# Generated by Django 4.0 on 2022-09-03 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_question_quiz_question_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='quiz_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.quiz'),
        ),
    ]
